// Generated by testcase:gen — edit via testcase YAML + re-gen with --force


import { expect, test } from '../fixtures/semantic-ui'




import { applyTestcaseMocks, applyTestcaseSession } from '../helpers/applyTestcaseMocks'

import { assertRequestMatches, expectNewTabWithUrl, whenNetworkRequest } from '../helpers/testcaseAssertions'


import { resolvePlaceholder, resolveTestcaseData, resolveTestIdTemplate } from '../helpers/testcaseData'

import { ChainHotelListPage } from '../pages/chain-hotels/ChainHotelListPage'



const TESTCASE_MOCKS = []




test.describe('chain-hotel-list', () => {

  test.beforeEach(async ({ page }) => {


    await applyTestcaseSession(page, 'mockChainAuthenticatedSession')


    await applyTestcaseMocks(page, TESTCASE_MOCKS)

  })



  test('Chain xem danh sách hotel', async ({ page, consoleErrors }) => {

    const po = new ChainHotelListPage(page)






    await po.goto('/hotels')








    await po.waitForTestId('chain-hotels-table')






    await po.expectTestIdVisible('chain-hotels-total-btn', true)


    await po.expectTestIdVisible('chain-hotels-per-page-select', true)


    await po.expectTestIdVisible('chain-hotels-export-month-input', true)


    await po.expectTestIdVisible('chain-hotels-search-form', false)





    await po.waitForSemanticReady()



    await expect(page).toHaveNoConsoleErrors(consoleErrors)


    await expect(page).toHaveNoHorizontalScroll({ rootSelector: '[data-testid="chain-hotels-page"]' })


    await expect(page).toHaveNoBrokenImages()



  })

})
