// Generated by testcase:gen — edit via testcase YAML + re-gen with --force


import { test } from '@playwright/test'




import { applyTestcaseMocks, applyTestcaseSession } from '../helpers/applyTestcaseMocks'

import { assertRequestMatches, expectNewTabWithUrl, whenNetworkRequest } from '../helpers/testcaseAssertions'


import { resolvePlaceholder, resolveTestcaseData, resolveTestIdTemplate } from '../helpers/testcaseData'

import { ChainHotelLoginAsManagerPage } from '../pages/chain-hotels/ChainHotelLoginAsManagerPage'



const TESTCASE_MOCKS = [
  {
    "method": "POST",
    "path": "/api/auth/store/login-from-admin",
    "response": "storeLoginFromAdminSuccess"
  }
]


const TESTCASE_DATA = resolveTestcaseData({
  "manager_id": "{{manager_id}}"
})




test.describe('chain-hotel-login-as-manager', () => {

  test.beforeEach(async ({ page }) => {


    await applyTestcaseSession(page, 'mockChainAuthenticatedSession')


    await applyTestcaseMocks(page, TESTCASE_MOCKS)

  })



  test('Chain login as manager mở store tab', async ({ page }) => {

    const po = new ChainHotelLoginAsManagerPage(page)


    const data = TESTCASE_DATA






    await po.goto('/hotels')








    await po.waitForTestId('chain-hotels-table')










    const networkResponseTab = whenNetworkRequest(page, {

      method: 'POST',

      path: '/api/auth/store/login-from-admin',

      bodyContains: {
  "id": "{{manager_id}}"
}

    })


    await expectNewTabWithUrl(page, async () => {

      await po.click(resolveTestIdTemplate('chain-hotels-cell-managers-login-as-{{manager_id}}', data))

    }, '/store/')


    await assertRequestMatches(await networkResponseTab, {

      method: 'POST',

      path: '/api/auth/store/login-from-admin',

      bodyContains: {
  "id": "{{manager_id}}"
}

    }, data)







  })

})
