// Generated by testcase:gen — edit via testcase YAML + re-gen with --force


import { test } from '@playwright/test'




import { applyTestcaseMocks, applyTestcaseSession } from '../helpers/applyTestcaseMocks'

import { assertRequestMatches, expectNewTabWithUrl, whenNetworkRequest } from '../helpers/testcaseAssertions'


import { resolvePlaceholder, resolveTestcaseData, resolveTestIdTemplate } from '../helpers/testcaseData'

import { ChainHotelExportReportPage } from '../pages/chain-hotels/ChainHotelExportReportPage'



const TESTCASE_MOCKS = [
  {
    "method": "POST",
    "path": "/api/hotels/export-report",
    "response": "chainHotelExportReportSuccess"
  }
]


const TESTCASE_DATA = resolveTestcaseData({
  "month": "{{last_month_yyyy_mm}}"
})




test.describe('chain-hotel-export-report', () => {

  test.beforeEach(async ({ page }) => {


    await applyTestcaseSession(page, 'mockChainAuthenticatedSession')


    await applyTestcaseMocks(page, TESTCASE_MOCKS)

  })



  test('Chain tải báo cáo 開封率データ', async ({ page }) => {

    const po = new ChainHotelExportReportPage(page)


    const data = TESTCASE_DATA






    await po.goto('/hotels')








    await po.waitForTestId('chain-hotels-table')








    await po.waitForRole('row', /Manager A/)








    await po.fill('chain-hotels-export-month-input', resolvePlaceholder('{{last_month_yyyy_mm}}', data))






    const networkResponse0 = whenNetworkRequest(page, {

      method: 'POST',

      path: '/api/hotels/export-report',

      bodyContains: {
  "month": "{{last_month_yyyy_mm}}"
}

    })




    await po.click('chain-hotels-export-report-btn')




    await assertRequestMatches(await networkResponse0, {

      method: 'POST',

      path: '/api/hotels/export-report',

      bodyContains: {
  "month": "{{last_month_yyyy_mm}}"
}

    }, data)







  })

})
