export { default as TagsInput } from '~/components/atoms/tags-input/TagsInput.vue'
export { default as TagsInputInput } from '~/components/atoms/tags-input/TagsInputInput.vue'
export { default as TagsInputItem } from '~/components/atoms/tags-input/TagsInputItem.vue'
export { default as TagsInputItemDelete } from '~/components/atoms/tags-input/TagsInputItemDelete.vue'
export { default as TagsInputItemText } from '~/components/atoms/tags-input/TagsInputItemText.vue'
